version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongoDB_container
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hoseok9823_db_user
      - MONGO_INITDB_ROOT_PASSWORD=asd4162557
      - MONGO_INITDB_DATABASE=weblotto
    volumes:
      - ./data:/data/db
